kind: PersistentVolume
apiVersion: v1
metadata:
  name: owncloud-config
  labels:
    app: owncloud
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    # The name here must match what was created with gcloud compute disks create ...
    pdName: owncloud-config-disk
    fsType: ext4
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: owncloud-data
  labels:
    app: owncloud
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: owncloud-data-disk
    fsType: ext4
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: owncloud-apps
  labels:
    app: owncloud
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: owncloud-apps-disk
    fsType: ext4
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mariadb-owncloud
  labels:
    app: owncloud
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mariadb-owncloud-disk
    fsType: ext4
